# 1
- Torch의 Tensor
- Tensor의 선언
- Numpy to Tensor
- Tensor to Numpy
- view
- cat
- mean, sum
- GPU 연산

In [4]:
import torch

x = torch.Tensor(3)
x

tensor([7.0062e+22, 4.5559e-41, 6.0735e-25])

In [5]:
x2 = torch.Tensor(3, 3)
x2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Tensor의 Random 선언
a = torch.rand(3, 3)
a

tensor([[0.6150, 0.2878, 0.4705],
        [0.8970, 0.8634, 0.4327],
        [0.1242, 0.2178, 0.3101]])

In [7]:
# normal distribution random 값으로 선언
a = torch.randn(3, 3)
a

tensor([[ 0.1560,  0.7746,  1.0326],
        [-1.1882, -0.5802, -0.1564],
        [-0.5510,  1.0210, -0.0040]])

In [8]:
# Numpy 에서 Tensor 로
import numpy as np
a = np.array([1, 2, 3, 4])
b = torch.Tensor(a)
b

tensor([1., 2., 3., 4.])

In [9]:
# Tensor 에서 Numpy 로
a = torch.rand(3, 3)
b = a.numpy()
b

array([[0.08342022, 0.1665942 , 0.17174852],
       [0.15058577, 0.7105323 , 0.85587627],
       [0.35589147, 0.22164148, 0.6660076 ]], dtype=float32)

In [15]:
# Tensor의 형태 변환 (view)

a = torch.rand(3, 3)
a = a.view(1, 1, 3, 3)
print(a.shape)
print(a)

torch.Size([1, 1, 3, 3])
tensor([[[[0.3393, 0.7249, 0.5822],
          [0.1551, 0.2113, 0.1342],
          [0.1564, 0.0822, 0.0653]]]])


In [18]:
# Tensor 합치기
# torch.cat((Tensor_A, Tensor_B), dim)

a = torch.randn(1, 1, 3, 3)
b = torch.randn(1, 1, 3, 3)
c = torch.cat((a, b), 0)
c

tensor([[[[ 0.4087, -0.3836, -0.1997],
          [ 0.9159, -0.0943, -2.0407],
          [-0.3011, -0.1097,  0.8523]]],


        [[[-1.4659,  0.1223, -1.3216],
          [-1.2374, -0.1963,  0.2494],
          [-0.8658, -1.2885,  1.4062]]]])

In [19]:
# Tensor 계산을 GPU로

x = torch.rand(3, 3)
y = torch.rand(3, 3)

if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()

print(x + y)

tensor([[1.6235, 0.8782, 1.0138],
        [0.9935, 0.9642, 1.2879],
        [1.0337, 1.7549, 1.0651]], device='cuda:0')


In [21]:
a = torch.rand(3 ,3)
print(a.mean())
print(a.sum())

tensor(0.4239)
tensor(3.8147)


# 2. Autograd와 Variable


Auto Gradient : 미분 값을 자동으로 계산해준다.  
자동 계산을 위해 사용하는 변수 -> Variable

In [23]:
from torch.autograd import Variable
a = torch.rand(5)
a = Variable(a)
a

tensor([0.1233, 0.5094, 0.6977, 0.5297, 0.2541])

Variable
- data : Tensor형태의 데이터가 담김
- grad : Data가 거쳐온 layer에 대한 미분값이 축적됨
    - Update를 위한 Gradient Descent Value가 저장되어있음
- grad_fn : 미분값을 계산한 함수에 대한 정보
    - 어떤 연산에 대한 backward를 진행을 했다. 라는 정보

In [25]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [35]:
# input으로 적용되는 a값같은 경우에는, requires_grad를 True로 지정을 해줘야 함
# True로 지정을 하지 않는다면, grad 값을 필요로 하지 않는다고 생각
a = Variable(a, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [44]:
print("------a.data------")
print(a.data)
print("------a.grad------")
print(a.grad)
print("------a.grad_fn------")
print(a.grad_fn)

------a.data------
tensor([[1., 1.],
        [1., 1.]])
------a.grad------
tensor([[6., 6.],
        [6., 6.]])
------a.grad_fn------
None


In [37]:
b = a + 2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [38]:
c = b ** 2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [39]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [40]:
print(out)
out.backward()

tensor(36., grad_fn=<SumBackward0>)


backward?
- a.grad의 값을 채워주는 역할

In [43]:
print("------a.data------")
print(a.data)
print("------a.grad------")
print(a.grad)
print("------a.grad_fn------")
print(a.grad_fn)

------a.data------
tensor([[1., 1.],
        [1., 1.]])
------a.grad------
tensor([[6., 6.],
        [6., 6.]])
------a.grad_fn------
None


In [45]:
print("------b.data------")
print(b.data)
print("------b.grad------")
print(b.grad)
print("------b.grad_fn------")
print(b.grad_fn)

------b.data------
tensor([[3., 3.],
        [3., 3.]])
------b.grad------
None
------b.grad_fn------


C:\Users\sangmin\anaconda3\lib\site-packages\torch\tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [46]:
print("------c.data------")
print(c.data)
print("------c.grad------")
print(c.grad)
print("------c.grad_fn------")
print(c.grad_fn)

------c.data------
tensor([[9., 9.],
        [9., 9.]])
------c.grad------
None
------c.grad_fn------


In [47]:
print("------out.data------")
print(out.data)
print("------out.grad------")
print(out.grad)
print("------out.grad_fn------")
print(out.grad_fn)

------out.data------
tensor(36.)
------out.grad------
None
------out.grad_fn------


In [52]:
x = torch.ones(3)
x = Variable(x, requires_grad=True)
y = x ** 2
z = y * 3
print(z)
grad = torch.Tensor([0.1, 1, 10])
z.backward(grad)

tensor([3., 3., 3.], grad_fn=<MulBackward0>)


In [53]:
print("------x.data------")
print(x.data)
print("------x.grad------")
print(x.grad)
print("------x.grad_fn------")
print(x.grad_fn)

------x.data------
tensor([1., 1., 1.])
------x.grad------
tensor([ 0.6000,  6.0000, 60.0000])
------x.grad_fn------
None


# 3. nn & nn.functional

- torch.nn.conv2d : weight, bias를 자체적으로 가지고 있음
- torch.nn.functional.conv2d : input, weight 자체를 직접 넣어준다.
    - 외부에서 만든 필터를 직접 만들어서 넣어주어야 함

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

In [29]:
input = torch.ones(1, 1, 3, 3)
filter = torch.ones(1, 1, 3, 3)

In [30]:
input = Variable(input, requires_grad=True)
print(input)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)


In [31]:
filter = Variable(filter)

In [32]:
out = F.conv2d(input, filter)

In [33]:
print(out)

tensor([[[[9.]]]], grad_fn=<MkldnnConvolutionBackward>)


In [34]:
out.backward()

In [35]:
print(out.grad_fn)

In [36]:
print(input.grad)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [37]:
input = Variable(torch.ones(1, 1, 3, 3), requires_grad = True)

filter = filter + 1

In [38]:
out = F.conv2d(input, filter)
out.backward()
print(out.grad_fn)
print(input.grad)

tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]])


In [44]:
input = torch.ones(1, 1, 3, 3)
input = Variable(input, requires_grad=True)
# input, output, cunnel size
# 1채널짜리가 들어가서, 1채널이 나오는데, 컨볼루션을 연산하는 필터의 크기는 3x3이다.
func = nn.Conv2d(1, 1, 3)
func.weight

Parameter containing:
tensor([[[[-0.1351, -0.0776,  0.0351],
          [ 0.2246, -0.0431,  0.1012],
          [-0.1868, -0.1229,  0.1610]]]], requires_grad=True)

In [45]:
out = func(input)
print(out)

tensor([[[[-0.1368]]]], grad_fn=<MkldnnConvolutionBackward>)


In [49]:
print(input.grad)

None


In [50]:
out.backward()

In [51]:
print(input.grad)

tensor([[[[-0.1351, -0.0776,  0.0351],
          [ 0.2246, -0.0431,  0.1012],
          [-0.1868, -0.1229,  0.1610]]]])


In [53]:
# 5 X 5
# pretrained model 사용
# weight값 직접 설정

input = torch.ones(1, 1, 5, 5)
input = Variable(input, requires_grad=True)

filter = nn.Conv2d(1, 1, 3, bias=None)
print(filter.weight)

Parameter containing:
tensor([[[[-0.0376,  0.0690,  0.0785],
          [ 0.0063, -0.0958,  0.0356],
          [-0.1103, -0.3263,  0.2562]]]], requires_grad=True)


In [54]:
filter.weight = torch.nn.Parameter(torch.ones(1, 1, 3, 3) + 1)

In [55]:
filter.weight

Parameter containing:
tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]], requires_grad=True)

In [56]:
out = filter(input)
print(out)

tensor([[[[18., 18., 18.],
          [18., 18., 18.],
          [18., 18., 18.]]]], grad_fn=<MkldnnConvolutionBackward>)


In [ ]:
# ReLu, sigmoid, tanh, Max Pooling
